mysql:
  image: 'mysql:5.7.17'
  restart: always
  ports:
    - '3306:3306'
  volumes:
    - /opt/docker/mysql/mysqlVolume:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456

redis:
  image: 'redis'
  restart: always
  ports:
    - '6379:6379'
	
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  ports:
    - '9090:80'
  links:
    - mysql:db

loveauth:
  image: 'centos-ssh:7.2'
  restart: always
  ports:
    - '3180:3180'
    - '50000:22'
  volumes:
    - /opt/docker/loveauth/:/data0/online/loveauth-3180
