---
- hosts: gfs_client01_172.16.1.150
  remote_user: ansible
  sudo: yes
  tasks:
  - name: remote copy decompress
    unarchive: src=/home/ansible/script/yml_file/taobao1.tar.gz dest=/usr/local copy=yes 
