---
- hosts: gfs_client01_172.16.1.150
  remote_user: ansible
  sudo: yes
  tasks:
  - name: copy local server to client remote dir
    template: src=/tmp/{{item}} dest=/tmp/
    with_items:
      - add_user.yml
      - copy_file.yml
      - del_user.yml
