--- 
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: etcd install
    yum: 
      state: latest 
      name: etcd

  - name: rsync etcd.conf
    template:
      src: files/etcd.conf.j2
      dest: /etc/etcd/etcd.conf
      owner: root
      group: root
      mode: 0664

  - name: Make sure a service is running
    systemd: 
      state: started 
      name: etcd

  - name: enable service etcd and ensure it is not masked
    systemd:
      name: etcd
      enabled: yes
      masked: no

  - name: restart etcd
    shell: systemctl daemon-reload && systemctl restart etcd
