--- 
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
  - name: etcd install
    yum: 
      state: latest 
      name: etcd

  - name: Make sure a service is running
    systemd: state=started name=etcd

  - name: enable service etcd and ensure it is not masked
    systemd:
      name: etcd
      enabled: yes
      masked: no
