--- 
- hosts: gfs_client01_172.16.1.150
  remote_user: ansible
  sudo: yes
  tasks:
  - name: ensure apache latest version
    yum: state=latest name=httpd

  - name: apache configure filec
    copy: src=/opt/httpd.conf dest=/etc/httpd/conf/httpd.conf force=yes
    notify:
       - restart httpd
  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
